# Generated by Django 5.1.2 on 2025-04-10 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leagues", "0006_league_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("division", models.CharField(max_length=50)),
                ("coach1", models.CharField(max_length=100)),
                ("coach2", models.CharField(max_length=100)),
                ("home_field_name", models.CharField(max_length=100)),
                ("home_field_address", models.CharField(max_length=500)),
                ("home_field_city", models.CharField(max_length=100)),
                ("home_field_zipcode", models.CharField(max_length=100)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="leagues.league",
                    ),
                ),
            ],
        ),
    ]
