# Generated by Django 5.1.7 on 2025-04-02 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="league",
            name="description",
        ),
        migrations.AddField(
            model_name="league",
            name="age",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="league",
            name="divisions",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="league",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="league",
            name="season",
            field=models.CharField(default="fall", max_length=20),
        ),
        migrations.AddField(
            model_name="league",
            name="sex",
            field=models.CharField(default=" ", max_length=10),
        ),
        migrations.AddField(
            model_name="league",
            name="year",
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name="league",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leagues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
