# Generated by Django 5.1.7 on 2025-04-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0002_remove_league_created_at_remove_league_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="sex",
            field=models.CharField(default="Co-ed", max_length=10),
        ),
        migrations.AlterField(
            model_name="league",
            name="year",
            field=models.PositiveIntegerField(),
        ),
    ]
