# Generated by Django 5.1.7 on 2025-04-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0003_alter_league_sex_alter_league_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="session",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="league",
            name="season",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="league",
            name="sex",
            field=models.CharField(default="", max_length=10),
        ),
    ]
