# Generated by Django 5.1.7 on 2025-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0005_league_created_at_alter_league_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
